[package]
name = "mtg-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10.6"
reqwest = { version = "0.12.5", features = ["blocking"] }
scraper = "0.20.0"
tokio = { version = "1.39.3", features = ["full"] }

[dev-dependencies]
mockito = "1.5.0"
