name: Get nice price
permissions:                # Job-level permissions configuration starts here
  contents: write           # 'write' access to repository contents
  pull-requests: write      # 'write' access to pull requests
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5 * * *'
    
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build and run
      run: cd mtg-rust && RUST_LOG=info cargo run

    - name: Upload scan Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dl_cards
        path: mtg-rust/dragonslair_cards

    - name: Upload scan Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mtg-rust/compared_prices
        path: compared_prices

    # - name: Upload scan Artifacts
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: ${{ matrix.scan_type }}
    #     path: alphaspel_cards
    
    - run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add -A
        git commit -m "generated"
        git push